Opetushallitus/jod-landing-page-ui

package-lock.json

- Use updated footer
https://jira.eduuni.fi/browse/OPHJOD-1210

OPHJOD-1210: Use updated footer

---

package-lock.json
src/i18n/fi/translation.json
src/routes/Home/Home.tsx
src/routes/Root/Root.tsx

Update landing page
- "More info" box is copied from yksilo-ui. Thinking of creating separate JIRA ticket for creating it it DS.
- Buttons in the "service" area does not have correct colors as the Button component does not allow to change background colors easily. Creating another JIRA ticket for this.
- The video block is not added yet as discussed in UI/UX PAMU meeting.
- Most of the links are not directing to actual page yet.
- "Ohjaajan osio" background image is flipped horizontally in design
https://jira.eduuni.fi/browse/OPHJOD-1212

OPHJOD-1212: Update landing page

---

src/routes/Home/Home.tsx
src/routes/Root/Root.tsx

Fix the background color to gray when over 1440px.
https://jira.eduuni.fi/browse/OPHJOD-1212

OPHJOD-1212: Fix background color

---

package-lock.json
src/routes/Home/Home.tsx

- Use ExternalLink in external cards
https://jira.eduuni.fi/browse/OPHJOD-1620

OPHJOD-1620: Use ExternalLink in external cards

---

src/components/LanguageButton/LanguageButton.tsx
src/components/LanguageMenu/LanguageMenu.tsx
src/hooks/useMenuClickHandler/index.ts
src/routes/Root/Root.tsx
src/routes/Root/loader.ts
src/routes/index.tsx

Add language selection to navigationbar
https://jira.eduuni.fi/browse/OPHJOD-1618

OPHJOD-1618: Add language selection to navigationbar

---

package-lock.json
src/routes/Home/Home.tsx

Update to use MoreInfo component from design system.
https://jira.eduuni.fi/browse/OPHJOD-1617

OPHJOD-1617: Update to use MoreInfo component

---

src/components/NavMenu/NavMenu.tsx
src/i18n/fi/translation.json
src/routes/Root/Root.tsx

Add sidenavigation
https://jira.eduuni.fi/browse/OPHJOD-1619

OPHJOD-1619: Add sidenavigation

---

src/routes/Home/Home.tsx

- Update service buttons to have desired colors as in design
- Pressed state or hover not known for these colors, so I winged it.
- Update the layout so that in wider screens it is possible to have three blocks in the same row (previously it was only two on the same row by mistake)
https://jira.eduuni.fi/browse/OPHJOD-1616

OPHJOD-1616: Update buttons to have specific colors and fix layout

---

package-lock.json
package.json
src/components/FeedbackModal/FeedbackModal.tsx
src/components/FormError/FormError.tsx
src/i18n/fi/translation.json
src/routes/Root/Root.tsx
src/utils/index.ts

Just the UI; no feedback is sent to anywhere.
- Add feedback modal
- no actual feedback is sent; only for visual purposes currently
https://jira.eduuni.fi/browse/OPHJOD-1654

OPHJOD-1654: Add feedback-modal UI

---

src/i18n/fi/translation.json

- Add skiplinks translation
https://jira.eduuni.fi/browse/OPHJOD-1706

OPHJOD-1706: Add skiplinks translation

---

package-lock.json
src/components/FeedbackModal/FeedbackModal.tsx
src/routes/Root/Root.tsx

- Add MatomoTracker
https://jira.eduuni.fi/browse/OPHJOD-1687

OPHJOD-1687: Add MatomoTracker

---

package-lock.json
src/components/NavMenu/NavMenu.tsx
src/i18n/fi/translation.json
src/routes/Root/NoMatch.tsx

* Update Design System
* Update NavMenu
https://jira.eduuni.fi/browse/OPHJOD-1777

OPHJOD-1777: Update DS and NavMenu

---

src/routes/Root/Root.tsx

- Add siteId handling for prod
https://jira.eduuni.fi/browse/OPHJOD-1687

OPHJOD-1687: Add siteId handling for prod

---

src/routes/Root/Root.tsx

- Update chatbot agents
https://jira.eduuni.fi/browse/OPHJOD-1882

OPHJOD-1882: Update chatbot agents

---

package-lock.json
src/components/NavMenu/NavMenu.tsx

* Update DS to move navigation menu to the right side of the screen
* Minor cleanup in PortalLink classes
https://jira.eduuni.fi/browse/OPHJOD-1895

OPHJOD-1895: Update DS to move the navigation menu to the right side

---

.github/workflows/deploy.yml

- Exclude pre-launch files
https://jira.eduuni.fi/browse/OPHJOD-1879

OPHJOD-1879: Exclude pre-launch files

---

public/manifest-en.json
public/manifest-fi.json
public/manifest-sv.json

- Use absolute paths in manifests
https://jira.eduuni.fi/browse/OPHJOD-1996

OPHJOD-1996: Use absolute paths in manifests

---

package-lock.json
src/i18n/en/translation.json
src/i18n/fi/translation.json
src/i18n/sv/translation.json
src/routes/BasicInformation/AboutService.tsx
src/routes/BasicInformation/Accessibility.tsx
src/routes/BasicInformation/AiUsage.tsx
src/routes/BasicInformation/BasicInformation.tsx
src/routes/BasicInformation/DataSources.tsx
src/routes/BasicInformation/PrivacyAndCookies.tsx
src/routes/BasicInformation/index.ts
src/routes/Root/Root.tsx
src/routes/index.tsx

- Add basic information pages
https://jira.eduuni.fi/browse/OPHJOD-2118

OPHJOD-2118: Add basic information pages

---

package-lock.json
src/i18n/fi/translation.json
src/routes/Root/Root.tsx
src/routes/index.tsx

- Add beta feedback banner.
- Update `@jod/design-system`
https://jira.eduuni.fi/browse/OPHJOD-2197

OPHJOD-2197: Add beta feedback banner

---

src/components/NavMenu/NavMenu.tsx
src/i18n/fi/translation.json

* Update navigation menu translations, ordering and DS
* Update the "portal link" colors and omit menuSection prop to the rid of the extra divider
https://jira.eduuni.fi/browse/OPHJOD-2241

OPHJOD-2241: Update navigation menu translations, ordering and DS

---

src/components/LanguageButton/LanguageButton.tsx

Fix LanguageButton's menu overlapping with the NoteStack
https://jira.eduuni.fi/browse/OPHJOD-2296

OPHJOD-2296: Fix LanguageButton overlapping NoteStack

---

src/routes/Home/Home.tsx

- Update background image
https://jira.eduuni.fi/browse/OPHJOD-2159

OPHJOD-2159: Update background image

---

src/routes/Home/Home.tsx

Refactor hero card position and fine tune gaps between sections
https://jira.eduuni.fi/browse/OPHJOD-2079

OPHJOD-2079: Refactor hero card position and fine tune gaps between sections

---

package-lock.json

- Update DS
https://jira.eduuni.fi/browse/OPHJOD-2234

OPHJOD-2234: Update DS

---

src/i18n/fi/translation.json
src/routes/Home/Home.tsx

Update translations and links. Open links in new tab. Switch sections to match latest designs. 
https://jira.eduuni.fi/browse/OPHJOD-2380

OPHJOD-2380: Update translations, set links to open in new tab

---

package-lock.json
src/components/ArticleAccordion/index.tsx

* Update DS
* Fix `Accordion` props
https://jira.eduuni.fi/browse/OPHJOD-2367

OPHJOD-2367: Update DS and fix Accodion props

---

package-lock.json
package.json
src/components/FeedbackModal/FeedbackModal.tsx
src/components/Toaster/Toaster.tsx
src/components/Toaster/toaster.css
src/routes/Root/Root.tsx

- Add toast for feedback messages
https://jira.eduuni.fi/browse/OPHJOD-2413

OPHJOD-2413: Add toast for feedback messages
